### ISSUE TITLE
Provide an option to download the JSON output

### ISSUE THREAD

**Issue by jeyakums** [he-yang/Excel-to-JSON#1]
Great Job in the add in.
It would be good if you can add a feature to save the output JSON as a file rather than Currently copy pasting from the page.

**Comment by he-yang** [comment]
Thank you for your message.
It's always great to hear that my work is of help to the others. :))
and
You may find the new feature in one of the coming new versions.

**Comment by he-yang** [comment]
fixed #1
close #1 
commit c43a95f
